name: 22 Train Generic Image Captioning
description: Image captioning training with compatible library versions
inputs:
  - name: tokenizer_json
    type: Model
  - name: vision_encoder_config
    type: Data
  - name: caption_dataset
    type: Dataset
  - name: training_parameters
    type: String
    default: "{}"
outputs:
  - name: trained_model
    type: Model
  - name: training_report
    type: Data
  - name: loss_curves
    type: Data
  - name: schema_json
    type: Data
implementation:
  container:
    image: gurpreetgandhi/nesy-factory:v29
    command:
      - sh
      - -c
      - |
        python3 -c "
        import sys, os, json, pickle, base64, io
        
        # Install compatible versions first - matching your environment
        import subprocess
        subprocess.run([sys.executable, '-m', 'pip', 'install', 'numpy==1.26.4', '--force-reinstall'], capture_output=True)
        subprocess.run([sys.executable, '-m', 'pip', 'install', 'torch==2.1.0', 'torchvision==0.16.0', 'transformers==4.37.2', '--force-reinstall'], capture_output=True)
        
        tokenizer_json_path = sys.argv[1]
        vision_encoder_config_path = sys.argv[2]
        caption_dataset_path = sys.argv[3]
        training_params_str = sys.argv[4]
        trained_model_path = sys.argv[5]
        training_report_path = sys.argv[6]
        loss_curves_path = sys.argv[7]
        schema_output_path = sys.argv[8]
        
        with open(vision_encoder_config_path, 'r') as f:
            vision_config = json.load(f)
        
        with open(caption_dataset_path, 'rb') as f:
            caption_data = pickle.load(f)
        
        training_params = json.loads(training_params_str)
        num_epochs = training_params.get('epochs', 1)
        learning_rate = training_params.get('learning_rate', 5e-5)
        batch_size = training_params.get('batch_size', 4)
        
        print('Training config:', num_epochs, 'epochs, lr=', learning_rate, 'batch_size=', batch_size)
        print('Loaded', len(caption_data), 'training samples')
        
        try:
            import torch
            print('PyTorch version:', torch.__version__)
            import numpy as np
            print('NumPy version:', np.__version__)
            
            from nesy_factory.language_model.image_tokenizer import HFTokenizer
            from nesy_factory.language_model.vision_encoders import CLIPVisionEncoder
            from transformers import AutoModelForCausalLM
            from PIL import Image
            
            device = 'cuda' if torch.cuda.is_available() else 'cpu'
            print('Using device:', device)
            
            # Initialize vision encoder
            vision_encoder = CLIPVisionEncoder(
                model_name=vision_config.get('model_name', 'openai/clip-vit-base-patch32'),
                projection_dim=vision_config.get('projection_dim', 512)
            )
            vision_encoder.model = vision_encoder.model.to(device)
            
            # Initialize tokenizer
            tokenizer = HFTokenizer()
            tokenizer.run(tokenizer_name='microsoft/git-base')
            
            # Initialize language model
            language_model = AutoModelForCausalLM.from_pretrained('microsoft/git-base')
            language_model = language_model.to(device)
            
            # Setup optimizer
            optimizer = torch.optim.AdamW(
                list(vision_encoder.model.parameters()) + list(language_model.parameters()),
                lr=learning_rate
            )
            
            train_losses = []
            
            # Training loop
            for epoch in range(num_epochs):
                epoch_loss = 0.0
                processed = 0
                
                for i, sample in enumerate(caption_data):
                    if 'image_data' in sample and 'caption' in sample:
                        try:
                            optimizer.zero_grad()
                            
                            # Process image
                            image_bytes = base64.b64decode(sample['image_data'])
                            image = Image.open(io.BytesIO(image_bytes))
                            image_features = vision_encoder.run([image])
                            
                            # Process caption text
                            inputs = tokenizer.tokenizer(
                                sample['caption'], 
                                return_tensors='pt', 
                                max_length=128, 
                                padding='max_length', 
                                truncation=True
                            )
                            
                            input_ids = inputs['input_ids'].to(device)
                            attention_mask = inputs['attention_mask'].to(device)
                            
                            # Fuse image and text features
                            text_embeddings = language_model.get_input_embeddings()(input_ids)
                            image_features_expanded = image_features.unsqueeze(1).to(device)
                            
                            # Ensure dimensions match for fusion
                            if image_features_expanded.shape[1] < text_embeddings.shape[1]:
                                # Pad image features to match text sequence length
                                padding = text_embeddings.shape[1] - image_features_expanded.shape[1]
                                image_features_expanded = torch.nn.functional.pad(
                                    image_features_expanded, 
                                    (0, 0, 0, padding)
                                )
                            elif image_features_expanded.shape[1] > text_embeddings.shape[1]:
                                # Truncate image features to match text sequence length
                                image_features_expanded = image_features_expanded[:, :text_embeddings.shape[1], :]
                            
                            fused_embeddings = text_embeddings + image_features_expanded
                            
                            # Forward pass
                            outputs = language_model(
                                inputs_embeds=fused_embeddings,
                                attention_mask=attention_mask,
                                labels=input_ids
                            )
                            
                            loss = outputs.loss
                            loss.backward()
                            optimizer.step()
                            
                            epoch_loss += loss.item()
                            processed += 1
                            
                            if processed % 20 == 0:
                                print(f'Processed {processed} samples, current loss: {loss.item():.4f}')
                                
                        except Exception as e:
                            print(f'Error processing sample {i}: {e}')
                            continue
                
                if processed > 0:
                    avg_loss = epoch_loss / processed
                    train_losses.append(avg_loss)
                    print(f'Epoch {epoch+1}: average loss={avg_loss:.4f}, samples={processed}')
            
            final_loss = train_losses[-1] if train_losses else 0.0
            
            # Save model
            os.makedirs(os.path.dirname(trained_model_path) or '.', exist_ok=True)
            torch.save({
                'language_model_state_dict': language_model.state_dict(),
                'vision_encoder_config': vision_config,
                'training_params': training_params
            }, trained_model_path)
            
            # Save training report
            report = {
                'status': 'success',
                'epochs_completed': len(train_losses),
                'final_loss': float(final_loss),
                'samples_processed': processed,
                'total_samples': len(caption_data),
                'device_used': device,
                'torch_version': torch.__version__,
                'numpy_version': np.__version__
            }
            
            os.makedirs(os.path.dirname(training_report_path) or '.', exist_ok=True)
            with open(training_report_path, 'w') as f:
                json.dump(report, f, indent=2)
            
            # Save loss curves
            loss_data = {
                'epochs': list(range(1, len(train_losses) + 1)),
                'train_loss': [float(loss) for loss in train_losses]
            }
            
            os.makedirs(os.path.dirname(loss_curves_path) or '.', exist_ok=True)
            with open(loss_curves_path, 'w') as f:
                json.dump(loss_data, f, indent=2)
            
            # Save schema
            schema = {
                'training_completed': True,
                'model_type': 'image_captioning',
                'final_loss': float(final_loss),
                'epochs_trained': len(train_losses),
                'vision_encoder': vision_config.get('model_name', 'openai/clip-vit-base-patch32'),
                'language_model': 'microsoft/git-base'
            }
            
            os.makedirs(os.path.dirname(schema_output_path) or '.', exist_ok=True)
            with open(schema_output_path, 'w') as f:
                json.dump(schema, f, indent=2)
            
            print('Training completed successfully')
            
        except Exception as e:
            print('Training failed:', e)
            import traceback
            traceback.print_exc()
            
            report = {'status': 'failed', 'error': str(e)}
            os.makedirs(os.path.dirname(training_report_path) or '.', exist_ok=True)
            with open(training_report_path, 'w') as f:
                json.dump(report, f, indent=2)
            sys.exit(1)
        " "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
    args:
      - {inputPath: tokenizer_json}
      - {inputPath: vision_encoder_config}
      - {inputPath: caption_dataset}
      - {inputValue: training_parameters}
      - {outputPath: trained_model}
      - {outputPath: training_report}
      - {outputPath: loss_curves}
      - {outputPath: schema_json}
