name: 2 Train Generic Image Captioning
description: Trains a generic image captioning model suitable for any domain using nesy-factory components.
inputs:
  - name: tokenizer_json
    type: Model
  - name: vision_encoder_config
    type: Data
  - name: model_config
    type: String
  - name: model_weights
    type: Model
  - name: model_py
    type: Data
  - name: caption_dataset
    type: Dataset
  - name: dataset_metadata
    type: DatasetInfo
outputs:
  - name: trained_model
    type: Model
  - name: training_report
    type: Data
  - name: loss_curves
    type: Data
  - name: schema_json
    type: Data
implementation:
  container:
    image: gurpreetgandhi/nesy-factory:v29
    command:
      - sh
      - -c
      - |
        python3 -c "
        import sys, os, json, pickle, torch
        
        print('Number of arguments:', len(sys.argv))
        print('Arguments:', sys.argv)
        
        # Get arguments from command line
        tokenizer_json_path = sys.argv[1]
        vision_encoder_config_path = sys.argv[2]
        model_config_str = sys.argv[3]  # Now a JSON string
        model_weights_path = sys.argv[4]
        model_py_path = sys.argv[5]
        caption_dataset_path = sys.argv[6]
        dataset_metadata_path = sys.argv[7]
        trained_model_path = sys.argv[8]
        training_report_path = sys.argv[9]
        loss_curves_path = sys.argv[10]
        schema_output_path = sys.argv[11]

        print('Starting generic image captioning training...')

        # Parse model config from JSON string with escape sequence handling
        try:
            # First, handle any escape sequences by loading the JSON
            model_config = json.loads(model_config_str)
            print('Successfully parsed model config from JSON string')
        except json.JSONDecodeError as e:
            print('ERROR: Failed to parse model config JSON: ' + str(e))
            print('Raw model config string: ' + model_config_str)
            
            # Try to handle common escape sequence issues
            try:
                # Replace common escape sequences
                cleaned_str = model_config_str.replace('\\\"', '\"').replace('\\\\', '\\')
                model_config = json.loads(cleaned_str)
                print('Successfully parsed after cleaning escape sequences')
            except:
                # Fallback to default config
                print('Using default model config due to parsing errors')
                model_config = {
                    'training_parameters': {
                        'learning_rate': 5e-5,
                        'num_epochs': 10,
                        'batch_size': 8,
                        'max_train_samples': 1000,
                        'gradient_accumulation_steps': 1,
                        'validation_split': 0.1
                    },
                    'language_model_name': 'microsoft/git-base'
                }

        # Extract training parameters from model config with defaults
        training_params = model_config.get('training_parameters', {})
        learning_rate = training_params.get('learning_rate', 5e-5)
        num_epochs = training_params.get('num_epochs', 10)
        batch_size = training_params.get('batch_size', 8)
        max_train_samples = training_params.get('max_train_samples', 1000)
        gradient_accumulation_steps = training_params.get('gradient_accumulation_steps', 1)
        validation_split = training_params.get('validation_split', 0.1)
        language_model_name = model_config.get('language_model_name', 'microsoft/git-base')

        print('Training parameters from model config:')
        print('Language model: ' + language_model_name)
        print('Learning rate: ' + str(learning_rate))
        print('Num epochs: ' + str(num_epochs))
        print('Batch size: ' + str(batch_size))
        print('Max train samples: ' + str(max_train_samples))
        print('Gradient accumulation steps: ' + str(gradient_accumulation_steps))
        print('Validation split: ' + str(validation_split))

        try:
            from nesy_factory.language_model.image_captioning_trainer import HFImageCaptioningTrainer
            print('Successfully imported HFImageCaptioningTrainer')
        except ImportError as e:
            error_msg = 'HFImageCaptioningTrainer import failed: ' + str(e)
            print('ERROR: ' + error_msg)
            
            error_report = {
                'status': 'error',
                'error': error_msg,
                'suggestion': 'Ensure nesy_factory is properly installed with image captioning components'
            }
            
            os.makedirs(os.path.dirname(training_report_path) or '.', exist_ok=True)
            with open(training_report_path, 'w') as f:
                json.dump(error_report, f, indent=2)
            
            sys.exit(1)

        # Load datasets
        with open(caption_dataset_path, 'rb') as f:
            caption_data = pickle.load(f)
        
        with open(dataset_metadata_path, 'rb') as f:
            dataset_meta = pickle.load(f)

        # Load vision encoder config
        with open(vision_encoder_config_path, 'r') as f:
            vision_config = json.load(f)

        print('Training generic image captioning model on ' + str(len(caption_data)) + ' images')
        print('Domain: ' + dataset_meta.get('caption_strategy', 'generic'))
        print('Classes: ' + str(dataset_meta.get('detected_classes', ['various'])))

        # Initialize trainer
        trainer = HFImageCaptioningTrainer()

        # Run training with parameters from model config
        results = trainer.run(
            vision_encoder_config=vision_config,
            language_model_name=language_model_name,
            dataset_name='generic_custom_dataset',
            max_train_samples=min(max_train_samples, len(caption_data)),
            learning_rate=learning_rate,
            num_epochs=num_epochs,
            batch_size=batch_size,
            gradient_accumulation_steps=gradient_accumulation_steps,
            output_dir=os.path.dirname(trained_model_path) or '.'
        )

        # Save trained model
        os.makedirs(os.path.dirname(trained_model_path) or '.', exist_ok=True)
        training_summary = {
            'status': 'completed',
            'training_results': results,
            'model_saved': trained_model_path,
            'dataset_info': dataset_meta,
            'training_parameters': {
                'learning_rate': learning_rate,
                'num_epochs': num_epochs,
                'batch_size': batch_size,
                'max_train_samples': max_train_samples,
                'gradient_accumulation_steps': gradient_accumulation_steps,
                'validation_split': validation_split
            },
            'model_config_used': model_config,
            'domain_adaptability': 'high',
            'supported_image_types': dataset_meta.get('detected_classes', ['generic'])
        }
        torch.save(training_summary, trained_model_path)

        # Save training report
        os.makedirs(os.path.dirname(training_report_path) or '.', exist_ok=True)
        with open(training_report_path, 'w') as f:
            json.dump(results, f, indent=2)

        # Save loss curves
        loss_data = {
            'train_losses': results.get('train_losses', []),
            'test_losses': results.get('test_losses', []),
            'learning_rates': results.get('learning_rates', [])
        }
        os.makedirs(os.path.dirname(loss_curves_path) or '.', exist_ok=True)
        with open(loss_curves_path, 'w') as f:
            json.dump(loss_data, f, indent=2)

        # Save schema
        schema = {
            'training_parameters': training_summary['training_parameters'],
            'dataset_info': dataset_meta,
            'results_summary': {
                'final_train_loss': results.get('train_losses', [])[-1] if results.get('train_losses') else None,
                'final_test_loss': results.get('test_losses', [])[-1] if results.get('test_losses') else None,
                'classes_learned': dataset_meta.get('detected_classes', []),
                'domain_adaptability': 'high'
            },
            'model_config_reference': model_config,
            'generic_capabilities': [
                'cross_domain_captioning',
                'multiple_image_types',
                'adaptive_descriptions',
                'zero_shot_understanding'
            ]
        }
        
        os.makedirs(os.path.dirname(schema_output_path) or '.', exist_ok=True)
        with open(schema_output_path, 'w') as f:
            json.dump(schema, f, indent=2)

        print('Generic image captioning training completed!')
        print('Trained model saved to: ' + trained_model_path)
        print('Training report saved to: ' + training_report_path)
        " "$0" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10"
    args:
      - {inputPath: tokenizer_json}
      - {inputPath: vision_encoder_config}
      - {inputValue: model_config}
      - {inputPath: model_weights}
      - {inputPath: model_py}
      - {inputPath: caption_dataset}
      - {inputPath: dataset_metadata}
      - {outputPath: trained_model}
      - {outputPath: training_report}
      - {outputPath: loss_curves}
      - {outputPath: schema_json}
